"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/Navbar";
import { Footer } from "./components/Footer";
import { usePathname } from "next/navigation";
import toast, { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const path = usePathname();

  return (
    <html lang="en">
      <body className=" min-h-screen flex flex-col justify-between">
        {path !== "/auth" && <Navbar />}
        {children}
        {path !== "/auth" && <Footer />}
        <Toaster
  position="top-right"
  reverseOrder={false}
/>
      </body>
    </html>
  );
}
